name: Build APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Получаем полный исторический контекст
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Get Commit Messages
      run: |
        COMMIT_MESSAGES=$(git log --format=%B --no-merges ${GITHUB_SHA}^..${GITHUB_SHA})
        echo "Commit Messages: $COMMIT_MESSAGES"

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: fft.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Notify Telegram
      run: |
        curl -X POST \
          -F chat_id=-1001885273120 \
          -F document=@app/build/outputs/apk/debug/app-debug.apk \
          -F caption="New APK build is ready! Commit Messages: $COMMIT_MESSAGES" \
          https://api.telegram.org/bot6988107847:AAFuR3RayZU98vmb9jAJGIm1K1iBmrKGnY0/sendDocument
